name: Implementar en páginas de Github

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_pages:
    name: Implementar en GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Obtener repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Instalar dependencias
        run: npm ci

      - name: Construir la aplicación
        run: npm run build

      - name: Cargar artefacto para despliegue
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Asegúrate de que esta ruta sea la carpeta de salida de tu build.

      - name: Implementar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
