name: Implementar en páginas de Github

on:
  push:
    branches:
      - main # O la rama principal de tu proyecto. Cambia 'develop' por 'main' o la rama que uses para tu proyecto.

jobs:
  build:
    name: Construir
    runs-on: ubuntu-latest
    steps:
      - name: Obtener repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Instalar paquetes y construir aplicación
        run: |
          npm ci
          npm run build

      - name: Cargar artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Asegúrate de que esta ruta sea la carpeta de salida de tu build.

  deploy:
    name: Implementar aplicación
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
